import 'package:flutter/material.dart';

class MenModel {
  String image;
  String name;
  double price;
  String des;
  String composition;
  Color? color;
  Color? color1;
  Color? color2;
  Color? color3;
  MenModel({
    required this.image,
    required this.name,
    required this.price,
    required this.des,
    required this.composition,
    required this.color,
    required this.color1,
    required this.color2,
    required this.color3,
  });
}

List<MenModel> _listMenModel = [
  MenModel(
    image: 'assets/men/m1.jpg',
    name: 'Slim Fit Jeans',
    price: 14.36,
    des: 'Knit joggers featuring side pockets with zipper, one pocket on the leg and elastic waistband.one pocket on the leg and elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.lightBlue,
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m17.jpg',
    name: 'Slim Fit Trousers',
    price: 17.74,
    des: 'Knit joggers featuring side pockets, graphic print at the front and elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.orange[100],
    color2: Colors.orange,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m2.jpg',
    name: 'T-shirt with Print',
    price: 26.99,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.white,
    color2: Colors.green,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m4.jpg',
    name: 'Premium Polo Shirt',
    price: 21.75,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.green[900],
    color2: Colors.black,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m5.jpg',
    name: 'Basic Tank Top',
    price: 16.36,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.white,
    color2: Colors.orange[500],
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m6.jpg',
    name: 'Crewneck T-shirt',
    price: 26.87,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.green[900],
    color1: Colors.blue,
    color2: Colors.white,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m7.jpg',
    name: 'Sweatshirt with Print',
    price: 16.11,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.black,
    color2: Colors.blue,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m8.jpg',
    name: 'Technical Cargo Jogger',
    price: 18.36,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.green[900],
    color2: Colors.orange[100],
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m9.jpg',
    name: 'Printed Swimming Shorts',
    price: 9.56,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.green[400],
    color2: Colors.white,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m10.jpg',
    name: 'Drawstring Bermuda Shorts',
    price: 14.10,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.black,
    color2: Colors.white,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m11.jpg',
    name: 'T-shirt With Print',
    price: 10.36,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.blue,
    color2: Colors.red,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m12.jpg',
    name: 'Straight Corduroy Shorts',
    price: 13.27,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.green,
    color2: Colors.red,
    color3: Colors.blue,
  ),
  MenModel(
    image: 'assets/men/m13.jpg',
    name: 'Hoodie With Print',
    price: 24.66,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.white,
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m14.jpg',
    name: 'Tie-Dye Jacket',
    price: 24.9,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.purple[900],
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m15.jpg',
    name: 'Cargo Trousers',
    price: 18.36,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
   composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.brown,
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m16.jpg',
    name: 'Sweatshirt With Print',
    price: 23.36,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.brown,
    color1: Colors.black,
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m17.jpg',
    name: 'Sweatpants With Print',
    price: 19.16,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.brown[300],
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m18.jpg',
    name: 'Sweatshirt With Print',
    price: 19.67,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.black,
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m19.jpg',
    name: 'Jogging Trousers',
    price: 16.96,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.white,
    color1: Colors.red,
    color2: null,
    color3: null,
  ),
  MenModel(
    image: 'assets/men/m20.jpg',
    name: 'Printed Sweatshirt',
    price: 20,
    des: 'Regular fit knit trousers featuring side pockets with zipper fastening and adjustable elastic waistband.',
    composition: '63.9% Cotton 36.1% Polyester',
    color: Colors.black,
    color1: Colors.white,
    color2: null,
    color3: null,
  ),
];

get listMenModel => _listMenModel;
